#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

: "${DATABASE_URL:?Environment variable DATABASE_URL must be set}"

# Wyciągnięcie hosta z DATABASE_URL
POSTGRES_HOST=$(echo "$DATABASE_URL" | sed -E 's|.*://[^@]+@([^:/]+).*|\1|')
POSTGRES_PORT=5432  # domyślny port PostgreSQL

# Czekanie na bazę
wait-for-it "${POSTGRES_HOST}:${POSTGRES_PORT}" -t 30

>&2 echo "PostgreSQL is available at ${POSTGRES_HOST}:${POSTGRES_PORT}"

exec "$@"